spring.application.name=school-hrm

spring.datasource.url=jdbc:postgresql://localhost:5432/schoolhrm?currentSchema=demo
spring.datasource.username=postgres
spring.datasource.password=db123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
